using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CraftyHookers.UserService.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class UserPasswordAutogenerated : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "PasswordAutogenerated",
                table: "Users",
                type: "bit",
                nullable: false,
                defaultValue: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "PasswordAutogenerated",
                table: "Users");
        }
    }
}
