using CraftyHookers.UserService.Application.Commands;
using CraftyHookers.UserService.Application.Notifications;
using CraftyHookers.UserService.Core.Entities;
using CraftyHookers.UserService.Core.Repositories;
using CraftyHookers.UserService.Core.Security;
using MediatR;
using Moq;

namespace CraftyHookers.UserService.Application.Tests.Commands
{
    public class AddUserCommandHandlerTests
    {
        private readonly Mock<IUserRepository> _repository = new();
        private readonly Mock<IPasswordHasher> _passwordHasher = new();
        private readonly Mock<IPasswordGenerator> _passwordGenerator = new();
        private readonly Mock<IPublisher> _publisher = new();
        private readonly AddUserCommandHandler _sut;

        public AddUserCommandHandlerTests()
        {
            _repository
                .Setup(r => r.AddUserAsync(It.IsAny<User>()))
                .ReturnsAsync((User user) => user);

            _sut = new AddUserCommandHandler(
                _repository.Object,
                _passwordHasher.Object,
                _passwordGenerator.Object,
                _publisher.Object);
        }

        [Fact]
        public async Task Handle_DefaultsDisplayNameToUserName_WhenDisplayNameIsBlank()
        {
            var user = new User { Email = "jdoe", DisplayName = "" };

            await _sut.Handle(new AddUserCommand(user), CancellationToken.None);

            Assert.Equal("jdoe", user.DisplayName);
        }

        [Fact]
        public async Task Handle_DoesNotOverwriteDisplayName_WhenAlreadySet()
        {
            var user = new User { Email = "jdoe", DisplayName = "Jane Doe" };

            await _sut.Handle(new AddUserCommand(user), CancellationToken.None);

            Assert.Equal("Jane Doe", user.DisplayName);
        }

        [Fact]
        public async Task Handle_HashesTheGeneratedPassword_AndFlagsItAsAutogenerated()
        {
            var user = new User { Email = "jdoe", DisplayName = "Jane Doe" };
            _passwordGenerator.Setup(g => g.Generate(It.IsAny<int>())).Returns("generated-password");
            _passwordHasher.Setup(h => h.Hash("generated-password")).Returns("hashed-value");

            await _sut.Handle(new AddUserCommand(user), CancellationToken.None);

            Assert.Equal("hashed-value", user.PasswordHash);
            Assert.True(user.PasswordAutogenerated);
        }

        [Fact]
        public async Task Handle_PersistsTheUserThroughTheRepository()
        {
            var user = new User { Email = "jdoe", DisplayName = "Jane Doe" };

            var result = await _sut.Handle(new AddUserCommand(user), CancellationToken.None);

            _repository.Verify(r => r.AddUserAsync(user), Times.Once);
            Assert.Same(user, result);
        }

        [Fact]
        public async Task Handle_PublishesUserCreatedNotification_WithTheGeneratedPassword()
        {
            var user = new User { Email = "jdoe", DisplayName = "Jane Doe" };
            _passwordGenerator.Setup(g => g.Generate(It.IsAny<int>())).Returns("generated-password");

            await _sut.Handle(new AddUserCommand(user), CancellationToken.None);

            _publisher.Verify(p => p.Publish(
                It.Is<UserCreatedNotification>(n => n.User == user && n.TemporaryPassword == "generated-password"),
                It.IsAny<CancellationToken>()),
                Times.Once);
        }
    }
}
