using CraftyHookers.UserService.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CraftyHookers.UserService.Infrastructure.Data.Configurations
{
    public class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> builder)
        {
            builder.HasIndex(u => u.Email).IsUnique();
            builder.Property(u => u.PasswordAutogenerated).HasDefaultValue(true);
            builder.Property(u => u.PasswordTS).HasDefaultValueSql("getdate()");
            builder.Property(u => u.AccountCreatedTS).HasDefaultValueSql("getdate()");
            builder.Property(u => u.UserId).HasDefaultValueSql("newsequentialid()");
        }
    }
}
