namespace CraftyHookers.UserService.Core.Entities
{
    public class User
    {
        public Guid UserId { get; set; } = Guid.NewGuid();
        public string DisplayName { get; set; } = null!;
        public string UserName { get; set; } = null!;
        public string PasswordHash { get; set; } = null!;
        public bool PasswordAutogenerated { get; set; }
        public DateTime PasswordTS { get; set; } = DateTime.UtcNow;
        public DateTime? AccountVerifiedTS { get; set; }
        public DateTime AccountCreatedTS { get; set; } = DateTime.UtcNow;
    }
}
