using CraftyHookers.UserService.Application.Notifications;
using CraftyHookers.UserService.Core.Entities;
using CraftyHookers.UserService.Core.Repositories;
using CraftyHookers.UserService.Core.Security;
using CraftyHookers.UserService.Core.Validation;
using MediatR;

namespace CraftyHookers.UserService.Application.Commands
{
    public record AddUserCommand(User user) : IRequest<User>;

    public class AddUserCommandHandler(IUserRepository repository, IPasswordHasher passwordHasher, IPasswordGenerator passwordGenerator, IPublisher publisher)
        : IRequestHandler<AddUserCommand, User>
    {
        public async Task<User> Handle(AddUserCommand request, CancellationToken cancellationToken)
        {
            if (!EmailValidator.IsValid(request.user.Email))
            {
                throw new ArgumentException($"'{request.user.Email}' is not a valid email address.", nameof(User.Email));
            }

            if (String.IsNullOrEmpty(request.user.DisplayName))
            {
                request.user.DisplayName = request.user.Email;
            }

            var temporaryPassword = passwordGenerator.Generate();
            request.user.PasswordHash = passwordHasher.Hash(temporaryPassword);
            request.user.PasswordAutogenerated = true;

            var createdUser = await repository.AddUserAsync(request.user);

            await publisher.Publish(new UserCreatedNotification(createdUser, temporaryPassword), cancellationToken);

            return createdUser;
        }
    }
}
